### ISSUE TITLE
'No Folder' view shows all items

### ISSUE THREAD

**Issue by treequell** [flathub/com.bitwarden.desktop#108] opened 2022-06-05 19:33 UTC
### Bug description

Clicking 'No Folder' shows all items in the vault.

### Steps to reproduce

1. Open Bitwarden vault,
2. Click 'No Folder' in left column under 'Folders' subheading,
3. Observe that all items in the vault are listed in the middle column, same as clicking 'All Items' in left column.

### Expected functionality

When clicking 'No Folder' In the left column, only the items that are not saved in a folder should be listed in the middle column.

### Other builds

The expected functionality is observed when running the Bitwarden-1.33.0-x86_64.AppImage. The expected functionality was also observed on previous versions of the com.bitwarden.desktop flatpak if I recall correctly.

### Flatpak info output

```
          ID: com.bitwarden.desktop
         Ref: app/com.bitwarden.desktop/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 2022.5.0
     License: GPL-3.0
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 299.1 MB
     Runtime: org.freedesktop.Platform/x86_64/21.08
         Sdk: org.freedesktop.Sdk/x86_64/21.08
```

**Comment by ghisvail** [comment] 2022-06-06 00:31
Could you try the following [AppImage](https://github.com/bitwarden/clients/releases/download/desktop-v2022.5.0/Bitwarden-2022.5.0-x86_64.AppImage)? I suspect this issue is not Flatpak specific and may be a regression introduced by version `2022.5.0`.

**Comment by treequell** [comment] 2022-06-06 00:42
`Bitwarden-2022.5.0-x86_64.AppImage` produces the same issue. So yes, you are correct.

Thanks!

**Comment by treequell** [comment] 2022-06-06 19:29
Upstream issue submitted: bitwarden/desktop/issues/1536

**Comment by ghisvail** [comment] 2022-08-14 07:20
Looks like the "No Folder" filter now works as intended. Closing.

**Closed by ghisvail** 2022-08-14 07:20 UTC
Labels: wontfix, upstream
