### ISSUE TITLE
bitwarden 1.28 does not launch to gui

### ISSUE THREAD

**Issue by martywd** [flathub/com.bitwarden.desktop#75] opened 2021-08-20 14:29 UTC
Updating flathub / com.bitwarden.desktop from 1.27.1 to 1.28, then attempting to start bitwarden 1.28 yields no gui app.

From a terminal, 'ps ax|grep -v grep|grep bitwarden' shows bitwarden processes running.

Kill all bitwarden processes, then running from a terminal these error messages:

```
marty@..... ~ $ flatpak run com.bitwarden.desktop
[2 preload-host-spawn-strategy] Running: /app/bin/zypak-helper child - /app/Bitwarden/bitwarden --type=zygote
A JavaScript error occurred in the main process
Uncaught Exception:
Error: libsecret-1.so.0: cannot open shared object file: No such file or directory
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1812)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1203:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2039)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/app/Bitwarden/resources/app.asar/node_modules/keytar/lib/keytar.js:1:14)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
Gtk-Message: 23:36:46.853: Failed to load module "xapp-gtk3-module"
libGL error: MESA-LOADER: failed to retrieve device information
MESA-LOADER: failed to retrieve device information
MESA-LOADER: failed to retrieve device information
```
OS: Linux Mint 20.2 MATE 64-bit
flatpak => v. 1.11.2-1flatpak1~20.04 amd64

I had to revert back to  flathub / com.bitwarden.desktop 1.27.1 to continuing using com.bitwarden.desktop.

.

**Comment by ghisvail** [comment] 2021-08-20 15:12
Duplicate of #72
Fixed by #73

Just update and it should be working now.

Next time, please consider checking if your issue has already been reported or fixed before opening a new issue. Thank you.

**Closed** 2021-08-20 15:24 UTC
Labels: duplicate
