### ISSUE TITLE
Start -> Crash

### ISSUE THREAD

**Issue by juxuanu** [flathub/com.bitwarden.desktop#74] opened 2021-08-20 09:07 UTC
```
╰─🚀 flatpak run com.bitwarden.desktop               
[2 preload-host-spawn-strategy] Running: /app/bin/zypak-helper child - /app/Bitwarden/bitwarden --type=zygote
A JavaScript error occurred in the main process
Uncaught Exception:
Error: libsecret-1.so.0: no sâha pogut obrir el fitxer dâobjecte compartit: El fitxer o directori no existeix
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1812)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1203:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2039)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/app/Bitwarden/resources/app.asar/node_modules/keytar/lib/keytar.js:1:14)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
Gtk-Message: 11:05:14.157: Failed to load module "canberra-gtk-module"
Gtk-Message: 11:05:14.157: Failed to load module "canberra-gtk-module"
libGL error: MESA-LOADER: failed to retrieve device information
libGL error: MESA-LOADER: failed to open amdgpu: /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/amdgpu_dri.so: no s’ha pogut obrir el fitxer d’objecte compartit: El fitxer o directori no existeix (search paths /usr/lib/x86_64-linux-gnu/GL/default/lib/dri)
libGL error: failed to load driver: amdgpu
```

Since the last update, it doesn't start.

**Comment by ghisvail** [comment] 2021-08-20 09:12
Duplicate of #72
Fixed by #73

**Closed by ghisvail** 2021-08-20 09:12 UTC
Labels: duplicate
