### ISSUE TITLE
Blank screen on Fedora 35 running on nouveau driver

### ISSUE THREAD

**Issue by ocosta** [flathub/com.bitwarden.desktop#82] opened 2021-11-13 02:07 UTC
Bitwarden was running just fine on Fedora 34, but this is not the case anymore with Fedora 35. All I see is a blank screen. If I run it from the console I get this:

```
[2 preload-host-spawn-strategy] Running: /app/bin/zypak-helper child - /app/Bitwarden/bitwarden --type=zygote
(node:2) DeprecationWarning: file property is deprecated and will be removed in v5.
(Use `bitwarden --trace-deprecation ...` to show where the warning was created)
Gtk-Message: 23:04:12.020: Failed to load module "canberra-gtk-module"
Gtk-Message: 23:04:12.020: Failed to load module "pk-gtk-module"
Gtk-Message: 23:04:12.020: Failed to load module "canberra-gtk-module"
Gtk-Message: 23:04:12.020: Failed to load module "pk-gtk-module"
[2:1112/230412.030234:ERROR:bus.cc(392)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2:1112/230412.127566:ERROR:bus.cc(392)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2:1112/230412.127621:ERROR:bus.cc(392)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2:1112/230412.127678:ERROR:bus.cc(392)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
LaunchProcess: failed to execvp:
xdg-settings
(node:2) electron: The default of nativeWindowOpen is deprecated and will be changing from false to true in Electron 15.  See https://github.com/electron/electron/issues/28511 for more information.
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[42:1112/230412.146760:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
(node:2) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'setContextMenu')
    at tray_main_TrayMain.updateContextMenu (/app/Bitwarden/resources/app.asar/main.js:2084:23)
    at messaging_main_MessagingMain.updateTrayMenu (/app/Bitwarden/resources/app.asar/main.js:1515:28)
    at messaging_main_MessagingMain.onMessage (/app/Bitwarden/resources/app.asar/main.js:1453:22)
    at messaging_main_MessagingMain.<anonymous> (/app/Bitwarden/resources/app.asar/main.js:1444:154)
    at Generator.next (<anonymous>)
    at /app/Bitwarden/resources/app.asar/main.js:1422:71
    at new Promise (<anonymous>)
    at messaging_main_awaiter (/app/Bitwarden/resources/app.asar/main.js:1418:12)
    at IpcMainImpl.<anonymous> (/app/Bitwarden/resources/app.asar/main.js:1444:82)
    at IpcMainImpl.emit (events.js:376:20)
(node:2) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
BTW I have [the same issue with Spotify](https://github.com/flathub/com.spotify.Client/issues/187), and this line appears on both stacktraces: `libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)`

**Comment by ghisvail** [comment] 2021-11-14 12:45
Duplicate of https://github.com/flathub/com.spotify.Client/issues/187

To be fixed upstream (Chromium, nouveau, both?)

**Comment by hevanaa** [comment] 2022-02-12 11:06
I also have a blank screen, but only under Wayland. In Gnome Xorg session, it works fine. It also works fine in Wayland if started with "--no-sandbox" argument.

**Comment by FilBot3** [comment] 2022-04-05 20:57
I also am having this running on Fedora 35 Silverblue with Nvidia Drivers on Xorg X11 session.

```bash
➜  ~ flatpak run com.bitwarden.desktop 
[2 preload-host-spawn-strategy] Running: /app/bin/zypak-helper child - /app/Bitwarden/bitwarden --type=zygote --enable-crashpad
(node:2) DeprecationWarning: file property is deprecated and will be removed in v5.
(Use `bitwarden --trace-deprecation ...` to show where the warning was created)
Gtk-Message: 15:52:28.382: Failed to load module "canberra-gtk-module"
Gtk-Message: 15:52:28.382: Failed to load module "canberra-gtk-module"
[2:0405/155228.393850:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[2:0405/155228.479570:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2:0405/155228.479618:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2:0405/155228.479646:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
LaunchProcess: failed to execvp:
xdg-settings
(node:2) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'setContextMenu')
    at TrayMain.updateContextMenu (/app/Bitwarden/resources/app.asar/main.js:52270:23)
    at MessagingMain.updateTrayMenu (/app/Bitwarden/resources/app.asar/main.js:54138:28)
    at MessagingMain.onMessage (/app/Bitwarden/resources/app.asar/main.js:54072:22)
    at MessagingMain.<anonymous> (/app/Bitwarden/resources/app.asar/main.js:54063:151)
    at Generator.next (<anonymous>)
    at /app/Bitwarden/resources/app.asar/main.js:54042:71
    at new Promise (<anonymous>)
    at messaging_main_awaiter (/app/Bitwarden/resources/app.asar/main.js:54038:12)
    at IpcMainImpl.<anonymous> (/app/Bitwarden/resources/app.asar/main.js:54063:79)
    at IpcMainImpl.emit (node:events:394:28)
(node:2) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'setContextMenu')
    at TrayMain.updateContextMenu (/app/Bitwarden/resources/app.asar/main.js:52270:23)
    at MessagingMain.updateTrayMenu (/app/Bitwarden/resources/app.asar/main.js:54138:28)
    at MessagingMain.onMessage (/app/Bitwarden/resources/app.asar/main.js:54072:22)
    at MessagingMain.<anonymous> (/app/Bitwarden/resources/app.asar/main.js:54063:151)
    at Generator.next (<anonymous>)
    at /app/Bitwarden/resources/app.asar/main.js:54042:71
    at new Promise (<anonymous>)
    at messaging_main_awaiter (/app/Bitwarden/resources/app.asar/main.js:54038:12)
    at IpcMainImpl.<anonymous> (/app/Bitwarden/resources/app.asar/main.js:54063:79)
    at IpcMainImpl.emit (node:events:394:28)
(node:2) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
15:52:34.597 › TypeError: Object has been destroyed
    at WindowMain.<anonymous> (/app/Bitwarden/resources/app.asar/main.js:52653:36)
    at Generator.next (<anonymous>)
    at /app/Bitwarden/resources/app.asar/main.js:52467:71
    at new Promise (<anonymous>)
    at window_main_awaiter (/app/Bitwarden/resources/app.asar/main.js:52463:12)
    at WindowMain.updateWindowState (/app/Bitwarden/resources/app.asar/main.js:52648:16)
    at WindowMain.<anonymous> (/app/Bitwarden/resources/app.asar/main.js:52602:28)
    at Generator.next (<anonymous>)
    at /app/Bitwarden/resources/app.asar/main.js:52467:71
    at new Promise (<anonymous>)
```

## Supporting information

Output of `/etc/os-release`

```bash
➜  ~ cat /etc/os-release 
NAME="Fedora Linux"
VERSION="35.20220403.0 (Silverblue)"
ID=fedora
VERSION_ID=35
VERSION_CODENAME=""
PLATFORM_ID="platform:f35"
PRETTY_NAME="Fedora Linux 35.20220403.0 (Silverblue)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:35"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora-silverblue/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=35
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=35
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Silverblue"
VARIANT_ID=silverblue
OSTREE_VERSION='35.20220403.0'
```

Neofetch

```bash
➜  ~ neofetch 
             .',;::::;,'.                filbot@radiant.lan 
         .';:cccccccccccc:;,.            ------------------ 
      .;cccccccccccccccccccccc;.         OS: Fedora Linux 35.20220403.0 (Silverblue) x86_64 
    .:cccccccccccccccccccccccccc:.       Kernel: 5.16.18-200.fc35.x86_64 
  .;ccccccccccccc;.:dddl:.;ccccccc;.     Uptime: 9 hours, 10 mins 
 .:ccccccccccccc;OWMKOOXMWd;ccccccc:.    Packages: 1412 (rpm), 84 (flatpak) 
.:ccccccccccccc;KMMc;cc;xMMc:ccccccc:.   Shell: bash 5.1.8 
,cccccccccccccc;MMM.;cc;;WW::cccccccc,   Resolution: 1920x1080 
:cccccccccccccc;MMM.;cccccccccccccccc:   DE: GNOME 41.4 
:ccccccc;oxOOOo;MMM0OOk.;cccccccccccc:   WM: Mutter 
cccccc:0MMKxdd:;MMMkddc.;cccccccccccc;   WM Theme: Adwaita 
ccccc:XM0';cccc;MMM.;cccccccccccccccc'   Theme: Adwaita [GTK2/3] 
ccccc;MMo;ccccc;MMW.;ccccccccccccccc;    Icons: Adwaita [GTK2/3] 
ccccc;0MNc.ccc.xMMd:ccccccccccccccc;     Terminal: gnome-terminal 
cccccc;dNMWXXXWM0::cccccccccccccc:,      CPU: AMD Ryzen 7 3800X (16) @ 3.900GHz 
cccccccc;.:odl:.;cccccccccccccc:,.       GPU: NVIDIA GeForce RTX 2070 SUPER 
:cccccccccccccccccccccccccccc:'.         Memory: 8788MiB / 32069MiB 
.:cccccccccccccccccccccc:;,..
  '::cccccccccccccc::;,.                                         
```                                                                 

`inxi` output

```bash
➜  ~ inxi --full
System:
  Host: radiant.lan Kernel: 5.16.18-200.fc35.x86_64 x86_64 bits: 64
    Desktop: GNOME 41.4 Distro: Fedora release 35 (Thirty Five)
Machine:
  Type: Desktop Mobo: ASUSTeK model: ROG STRIX X570-E GAMING v: Rev X.0x
    serial: <superuser required> UEFI: American Megatrends v: 1404
    date: 11/08/2019
CPU:
  Info: 8-core model: AMD Ryzen 7 3800X bits: 64 type: MT MCP cache:
    L2: 4 MiB
  Speed (MHz): avg: 2198 min/max: 2200/4559 cores: 1: 1863 2: 2235 3: 2197
    4: 2196 5: 1863 6: 2023 7: 2196 8: 2195 9: 2195 10: 2197 11: 2195 12: 2195
    13: 2178 14: 3367 15: 2207 16: 1866
Graphics:
  Device-1: NVIDIA TU104 [GeForce RTX 2070 SUPER] driver: nvidia v: 510.60.02
  Device-2: Logitech C920 HD Pro Webcam type: USB
    driver: snd-usb-audio,uvcvideo
  Display: wayland server: X.Org v: 1.21.1.4 with: Xwayland v: 21.1.4
    compositor: gnome-shell driver: X: loaded: nvidia
    unloaded: fbdev,modesetting,nouveau,vesa gpu: nvidia resolution:
    1: 1920x1080~60Hz 2: 1920x1080~60Hz
  OpenGL: renderer: NVIDIA GeForce RTX 2070 SUPER/PCIe/SSE2
    v: 4.6.0 NVIDIA 510.60.02
Audio:
  Device-1: NVIDIA TU104 HD Audio driver: snd_hda_intel
  Device-2: AMD Starship/Matisse HD Audio driver: snd_hda_intel
  Device-3: Logitech G733 Gaming Headset type: USB
    driver: hid-generic,snd-usb-audio,usbhid
  Device-4: Logitech C920 HD Pro Webcam type: USB
    driver: snd-usb-audio,uvcvideo
  Sound Server-1: ALSA v: k5.16.18-200.fc35.x86_64 running: yes
  Sound Server-2: PipeWire v: 0.3.49 running: yes
Network:
  Device-1: Intel Wi-Fi 6 AX200 driver: iwlwifi
  IF: wlp5s0 state: down mac: xxxxxxxxxxxxxxxxxx
  Device-2: Realtek RTL8125 2.5GbE driver: r8169
  IF: enp6s0 state: up speed: 1000 Mbps duplex: full mac: xxxxxxxxxxxxxx
  Device-3: Intel I211 Gigabit Network driver: igb
  IF: enp7s0 state: down mac: xxxxxxxxxxxxxxxxxx
Bluetooth:
  Device-1: Intel AX200 Bluetooth type: USB driver: btusb
  Report: rfkill ID: hci0 state: up address: see --recommends
Drives:
  Local Storage: total: 1.82 TiB used: 248.41 GiB (13.3%)
  ID-1: /dev/nvme0n1 vendor: Crucial model: CT1000P1SSD8 size: 931.51 GiB
  ID-2: /dev/nvme1n1 vendor: Samsung model: SSD 980 1TB size: 931.51 GiB
Partition:
  ID-1: /boot size: 973.4 MiB used: 80 MiB (8.2%) fs: ext4
    dev: /dev/nvme0n1p2
  ID-2: /boot/efi size: 598.8 MiB used: 9.8 MiB (1.6%) fs: vfat
    dev: /dev/nvme0n1p1
Swap:
  ID-1: swap-1 type: zram size: 8 GiB used: 0 KiB (0.0%) dev: /dev/zram0
Sensors:
  Message: No sensor data found. Is lm-sensors configured?
Info:
  Processes: 521 Uptime: 9h 10m Memory: 31.32 GiB used: 9.03 GiB (28.8%)
  Shell: Zsh inxi: 3.3.13
```

Flatpak Information

```bash
➜  ~ flatpak --version
Flatpak 1.12.7

➜  ~ flatpak list --app
Name                                      Application ID                                       Version                    Branch           Origin                      Installation
Bitwarden                                 com.bitwarden.desktop                                1.32.1                     stable           flathub-user                user
```

**Comment by ghisvail** [comment] 2022-04-06 08:30
@FilBot3 Thanks for providing your details.

It works fine on my end on Ubuntu 22.04 with nvidia drivers 510.

Sounds like the common denominator here is Fedora 35. Maybe worth getting their input as well.

**Comment by FilBot3** [comment] 2022-04-06 12:35
How would we want to get "Fedora"s input?

**Comment by FilBot3** [comment] 2022-04-06 12:39
I'm not sure what I did or what happened, but I uninstalled the Flatpak via GNOME Software. Waited overnight, rebooted and reinstalled it. Now it's working. I was going to say that Flatseal shows `XDG_DEFAULT_DESKTOP=Unity` and ask if that was Ubuntu specific possibly causing issues on Fedora, but now that's debunked. We'll see if it persists. 

@ocosta, try doing this to see if you can purge it and then reinstall it after a reboot.

```bash
flatpak uninstall com.bitwarden.desktop --delete-data
```

**Comment by ocosta** [comment] 2022-05-06 12:33
Thanks @FilBot3 , but forgot to mention here that I had to reinstall F35 on a new machine, and for some reason BitWarden started working as expected. Perhaps I should close this issue...?

**Comment by ghisvail** [comment] 2022-05-10 18:19
>  Perhaps I should close this issue...?

I will, thanks.

**Closed by ghisvail** 2022-05-10 18:19 UTC
Labels: upstream

**Comment by FilBot3** [comment] 2022-05-12 22:08
I still get some random instances where the GUI doesn't show up, and other times it does. I don't have a good reason for any kind of consistency other than maybe it's Wayland or GNOME or something. Just like as I type this and decide to check, it doesn't work. It worked yesterday before I upgraded to F36 Silverblue GNOME too. So, idk how to help more.

![image](https://user-images.githubusercontent.com/3039509/168175911-fbbd5a27-c676-479b-b066-d04ecbb523b2.png)
